[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "/usr/local/bin/solc"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[dependencies]
# openzeppelin = {git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", tag = "v4.7.3" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
